---
- name: Import facts
  ansible.builtin.import_role:
    name: k3s
    tasks_from: facts

- name: Role Validation
  ansible.builtin.import_tasks:
    file: validation.yaml

- name: Helm Dependencies
  when: ansible_host in k3s_server_hosts
  block:
    - name: Install packages
      ansible.builtin.apt:
        name: '{{ item }}'
        autoremove: true
        update_cache: true
      loop:
        - apt-transport-https
        - python3-kubernetes

    - name: Get file status
      ansible.builtin.stat:
        path: /usr/share/keyrings/{{ helm_vars.release.helm.key }}
      changed_when: not gpg_key.stat.exists
      register: gpg_key

    - name: Helm Package
      when: not gpg_key.stat.exists
      block:
        - name: Download key
          ansible.builtin.get_url:
            url: '{{ helm_release_key }}'
            dest: /tmp/{{ helm_vars.release.helm.repository.key }}
            owner: root
            group: root
            mode: '0644'
          register: result
          delay: 1
          retries: 3
          until: result is not failed

        - name: Dearmor key
          ansible.builtin.command:
            cmd: gpg --dearmor -o /usr/share/keyrings/{{ helm_vars.release.helm.key }} /tmp/{{ helm_vars.release.helm.repository.key }}
          changed_when: true

        - name: Delete key
          ansible.builtin.file:
            path: /tmp/{{ helm_vars.release.helm.repository.key }}
            state: absent

        - name: Get architecture
          ansible.builtin.command:
            cmd: dpkg --print-architecture
          changed_when: false
          register: architecture

        - name: Install repository
          ansible.builtin.deb822_repository:
            architectures: '{{ architecture.stdout }}'
            components: main
            name: helm-{{ helm_vars.release.helm.repository.channel }}
            signed_by: /usr/share/keyrings/{{ helm_vars.release.helm.key }}
            suites: all
            uris: '{{ helm_release_channel }}/{{ helm_vars.release.helm.distro }}/'
            enabled: true
            trusted: true

    - name: Helm Plugins
      block:
        - name: Install plugin packages
          ansible.builtin.apt:
            name: '{{ item }}'
            autoremove: true
            update_cache: true
          loop:
            - helm
            - python3-jsonpatch

        - name: Install plugin
          kubernetes.core.helm_plugin:
            plugin_path: '{{ helm_plugin_release_url }}'
            plugin_version: '{{ helm_vars.release.plugin.version }}'
          register: result
          delay: 1
          retries: 3
          until: result is not failed
