---
- name: Import facts
  ansible.builtin.import_role:
    name: k3s
    tasks_from: facts

- name: Role Reset
  when: ansible_host in k3s_server_hosts
  block:
    - name: Remove Helm Plugin
      when: helm_vars.release.plugin.enabled
      block:
        - name: Remove plugin
          kubernetes.core.helm_plugin:
            plugin_name: '{{ helm_vars.release.plugin.name }}'
            state: absent
          when:
            - "'helm' in ansible_facts.packages"
            - "'python3-kubernetes' in ansible_facts.packages"

        - name: Remove plugin package
          ansible.builtin.apt:
            name: python3-jsonpatch
            state: absent
            autoremove: true
            clean: true
            purge: true
          when: prompt_remove_packages in ['y', 'Y']

    - name: Remove Helm Packages
      when: prompt_remove_packages in ['y', 'Y']
      block:
        - name: Remove packages
          ansible.builtin.apt:
            name: '{{ item }}'
            state: absent
            autoremove: true
            clean: true
            purge: true
          loop:
            - apt-transport-https
            - helm
            - python3-kubernetes

        - name: Remove configuration files
          ansible.builtin.file:
            name: '{{ item }}'
            state: absent
          loop:
            - /etc/apt/sources.list.d/helm-{{ helm_vars.release.helm.repository.channel }}.sources
            - /usr/share/keyrings/{{ helm_vars.release.helm.key }}
