---
- name: Set facts
  ansible.builtin.import_tasks:
    file: facts.yaml

- name: Validate plugin release url
  ansible.builtin.uri:
    url: '{{ helm_plugin_release_url }}/releases/tag/{{ helm_vars.release.plugin.version }}'
    timeout: 5
  run_once: true
  register: result
  delay: 1
  retries: 3
  until: result is not failed

- name: Validate release key url
  ansible.builtin.uri:
    url: '{{ helm_release_key }}'
    timeout: 5
  run_once: true
  register: result
  delay: 1
  retries: 3
  until: result is not failed
