---
- name: Cluster Validation
  hosts: cluster
  become: true
  gather_facts: true
  tasks:
    - name: Validate global settings
      ansible.builtin.include_role:
        name: '{{ item }}'
        tasks_from: validation
      loop:
        - cluster
        - helm
        - k3s
        - kured
        - argocd
        - certmanager
        - cilium
        - longhorn
        - prometheus
        - sealedsecrets
