---
kured_vars:
  kubernetes:
    configuration:
      concurrency: 1
      lock:
        release_delay: 1m
        ttl: 5m
      log_format: text
      period: 15m
      reboot_delay: 30s
      time:
        start: '04:00'
        end: '08:00'
        zone: UTC
    helm:
      chart:
        name: kured
        org: kubereboot
        version: 5.4.5
      repository:
        name: charts
        org: kubereboot
        url: https://kubereboot.github.io
    metrics:
      create: 'true'
    namespace: kube-system
    resources:
      limits:
        cpu: 400m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 64Mi
    service:
      annotations:
        - key: prometheus.io/path
          value: /metrics
        - key: prometheus.io/port
          value: 8080
        - key: prometheus.io/scrape
          value: 'true'
      create: 'true'
      name: kured
