---
- name: Set project chart fact
  ansible.builtin.set_fact:
    sealedsecrets_project_chart: '{{ sealedsecrets_vars.kubernetes.helm.repository.org }}/{{ sealedsecrets_vars.kubernetes.helm.repository.name }}'
  run_once: true

- name: Set project url fact
  ansible.builtin.set_fact:
    sealedsecrets_project_url: https://github.com/{{ sealedsecrets_project_chart }}/releases
  run_once: true

- name: Set project tag url fact
  ansible.builtin.set_fact:
    sealedsecrets_project_url_tag: '{{ sealedsecrets_project_url }}/tag/helm-{{ sealedsecrets_vars.kubernetes.helm.chart.version }}'
  run_once: true

- name: Set release fact
  ansible.builtin.set_fact:
    sealedsecrets_release: '{{ sealedsecrets_vars.release.repository.org }}/{{ sealedsecrets_vars.release.repository.name }}'
  run_once: true

- name: Set release checksums fact
  ansible.builtin.set_fact:
    sealedsecrets_release_checksums: '{{ sealedsecrets_vars.release.version }}/{{ sealedsecrets_vars.release.checksums }}'
  run_once: true

- name: Set release file fact
  ansible.builtin.set_fact:
    sealedsecrets_release_file: '{{ sealedsecrets_vars.release.version }}/{{ sealedsecrets_vars.release.file }}'
  run_once: true

- name: Set release url fact
  ansible.builtin.set_fact:
    sealedsecrets_release_url: https://github.com/{{ sealedsecrets_release }}/releases
  run_once: true

- name: Set release checksums url fact
  ansible.builtin.set_fact:
    sealedsecrets_release_url_checksums: '{{ sealedsecrets_release_url }}/download/{{ sealedsecrets_release_checksums }}'
  run_once: true

- name: Set release file url fact
  ansible.builtin.set_fact:
    sealedsecrets_release_url_file: '{{ sealedsecrets_release_url }}/download/{{ sealedsecrets_release_file }}'
  run_once: true
