---
longhorn_vars:
  kubernetes:
    default_settings:
      data_locality: strict-local
      pod_deletion_policy: delete-both-statefulset-and-deployment-pod
      replica_count: 3
    frontend:
      loadbalancer:
        ip: 192.168.4.20
    helm:
      chart:
        name: longhorn
        version: v1.6.1
      repository:
        name: longhorn
        url: https://charts.longhorn.io
    gateway:
      service: longhorn-frontend
      subdomain: longhorn
    namespace: kube-system
    persistence:
      data_locality: best-effort
      migratable: true
      replica_count: 3
