---
certmanager_vars:
  kubernetes:
    cainjector:
      resources:
        limits:
          cpu: 400m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 64Mi
    controller:
      resources:
        limits:
          cpu: 400m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 64Mi
    helm:
      chart:
        name: cert-manager
        org: cert-manager
        version: v1.14.4
      repository:
        name: cert-manager
        org: jetstack
        url: https://charts.jetstack.io
    namespace: kube-system
    tls:
      cluster_issuer:
        name: certmanager-cluster-issuer
    webhook:
      resources:
        limits:
          cpu: 400m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 64Mi
