---
certmanager_vars:
  kubernetes:
    cluster:
      issuer:
        name: certmanager-cluster-issuer
    helm:
      chart:
        name: cert-manager
        org: cert-manager
        version: v1.14.4
      repository:
        name: cert-manager
        org: jetstack
        url: https://charts.jetstack.io
    namespace: kube-system
