---
- name: Import facts
  ansible.builtin.include_role:
    name: '{{ item }}'
    tasks_from: facts
  loop:
    - k3s
    - prometheus

- name: Role Validation
  ansible.builtin.import_tasks:
    file: validation.yaml

- name: Add repository
  kubernetes.core.helm_repository:
    name: '{{ certmanager_vars.kubernetes.helm.repository.org }}'
    repo_url: '{{ certmanager_vars.kubernetes.helm.repository.url }}'
  when: ansible_host in k3s_server_hosts

- name: Chart Setup
  when: ansible_host == k3s_server_default_host
  block:
    - name: Install chart
      kubernetes.core.helm:
        chart_ref: '{{ certmanager_project_chart }}'
        chart_version: '{{ certmanager_vars.kubernetes.helm.chart.version }}'
        kubeconfig: '{{ k3s_vars.directory.config }}/k3s.yaml'
        name: '{{ certmanager_vars.kubernetes.helm.chart.name }}'
        namespace: '{{ certmanager_vars.kubernetes.namespace }}'
        update_repo_cache: true
        values: "{{ lookup('ansible.builtin.template', 'values.j2') | from_yaml }}"
        wait: true
      register: result
      delay: 1
      retries: 3
      until: result is not failed

    - name: Create self-signed cluster issuer
      kubernetes.core.k8s:
        definition: "{{ lookup('ansible.builtin.template', 'cluster_issuer.j2') | from_yaml }}"
        kubeconfig: '{{ k3s_vars.directory.config }}/k3s.yaml'
        wait: true
