---
- name: Set facts
  ansible.builtin.import_tasks:
    file: facts.yaml

- name: Validate project tag url
  ansible.builtin.uri:
    url: '{{ kured_project_url_tag }}'
    timeout: 5
  run_once: true
  register: result
  delay: 1
  retries: 3
  until: result is not failed
