---
- name: Set facts
  ansible.builtin.import_tasks:
    file: facts.yaml

- name: Validate release binary url
  ansible.builtin.uri:
    url: '{{ k3s_release_url_file }}'
    timeout: 5
  run_once: true
  register: result
  delay: 1
  retries: 3
  until: result is not failed

- name: Validate release checksum url
  ansible.builtin.uri:
    url: '{{ k3s_release_url_checksum }}'
    timeout: 5
  run_once: true
  register: result
  delay: 1
  retries: 3
  until: result is not failed
