---
- name: Import facts
  ansible.builtin.include_role:
    name: '{{ item }}'
    tasks_from: facts
  loop:
    - cloudflare
    - cluster
    - k3s

- name: Cloudflare Setup
  when:
    - ansible_host == k3s_server_default_host
    - cloudflare_vars.kubernetes.gateway.domain != 'disabled'
  block:
    - name: Create api token
      kubernetes.core.k8s:
        definition: "{{ lookup('ansible.builtin.template', 'api_token.j2') | from_yaml }}"
        kubeconfig: '{{ k3s_vars.directory.config }}/k3s.yaml'
        wait: true
      no_log: true

    - name: Create cluster issuer
      kubernetes.core.k8s:
        definition: "{{ lookup('ansible.builtin.template', 'cluster_issuer.j2') | from_yaml }}"
        kubeconfig: '{{ k3s_vars.directory.config }}/k3s.yaml'
        wait: true
